upstream front {
    server myapp-front-blue-1:80;
    server myapp-front-blue-2:80;
}

upstream member {
    server myapp-member-green-1:8080;
    server myapp-member-green-2:8080;
}

upstream board {
    server myapp-board-green-1:8080;
    server myapp-board-green-2:8080;
}

server {
    listen 80;
    server_name localhost;

    location = /member {
        return 301 /member/;
    }

    location /member/ {
        proxy_pass http://member/;
    }

    location = /board {
        return 301 /board/;
    }

    location /board/ {
        proxy_pass http://board/;
    }

    location / {
        proxy_pass http://front;
    }
}
