upstream front {
    server myapp-front-blue-1:80;
    server myapp-front-blue-2:80;
}

upstream member {
    server myapp-member-green-1:8080;
    server myapp-member-green-2:8080;
}

upstream board {
    server myapp-board-green-1:8080;
    server myapp-board-green-2:8080;
}

server {
    listen 80;
    server_name localhost;

    location = /member {
        return 301 /member/;
    }

    location /member/ {
        proxy_pass http://member/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 3s;
        proxy_read_timeout 60s;
    }

    location = /board {
        return 301 /board/;
    }

    location /board/ {
        proxy_pass http://board/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 3s;
        proxy_read_timeout 60s;
    }

    location / {
        proxy_pass http://front;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 3s;
        proxy_read_timeout 60s;
    }
}